<?php

namespace Core\Entity;

/**
 * TasklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TasklistRepository extends \Doctrine\ORM\EntityRepository
{
}
